# Generated by Django 5.1.2 on 2025-03-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile'),
    ]

    operations = [

    ]
